# Tensorflow tensor操作

```
本片博文介绍和tensor相关的操作
```

In [1]:
import tensorflow as tf
sess = tf.InteractiveSession()

定义两个矩阵：

In [2]:
import numpy as np

matrix1 = tf.constant(np.arange(9).reshape(3,3), name="m1", dtype="int32")
matrix2 = tf.range(10,19, name="m2")

* 获取尺寸

In [3]:
matrix1.get_shape()

TensorShape([Dimension(3), Dimension(3)])

* 改变尺寸

In [4]:
matrix2.get_shape()

TensorShape([Dimension(9)])

In [6]:
matrix2 = tf.reshape(matrix2, (3,3))

In [7]:
matrix2.get_shape()

TensorShape([Dimension(3), Dimension(3)])

* 获取名字

In [8]:
matrix1.name

u'm1:0'

* 获取数据类型

In [9]:
matrix1.dtype

tf.int32

* 获取包含此tensor的graph

In [10]:
matrix1.graph

* 获取输出这个tensor的op

In [11]:
matrix1.op

* 求和：

In [52]:
tf.reduce_sum(matrix1, 1).eval() #对axis1

array([ 3, 12, 21], dtype=int32)

In [53]:
tf.reduce_mean(matrix2,0)

<tf.Tensor 'Mean_1:0' shape=() dtype=int32>

* 获取输入需要这个tensor的op

In [54]:
matrix1.consumers()

* 按维度连接

In [62]:
tf.concat(0, [matrix1, matrix2]).eval()

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]], dtype=int32)

In [63]:
tf.concat(1, [matrix1, matrix2]).eval()

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15],
       [ 6,  7,  8, 16, 17, 18]], dtype=int32)

* squeeze: 去掉维度尺寸为1的那一维

In [75]:
arr = tf.truncated_normal([3,4,1,6,1], stddev=0.1)

In [87]:
tf.shape(arr).eval()

array([3, 4, 1, 6, 1], dtype=int32)

In [88]:
tf.shape(tf.squeeze(arr)).eval()

array([3, 4, 6], dtype=int32)

* expand:和squeeze正好相反，扩展指定的维度为1

In [86]:
tf.shape(arr).eval()

array([3, 4, 1, 6, 1], dtype=int32)

In [85]:
tf.shape(tf.expand_dims(arr, 0)).eval()

array([1, 3, 4, 1, 6, 1], dtype=int32)

* split: 切分数据

In [79]:
split0, split1, split2 = tf.split(1, 3, matrix1)

In [81]:
tf.shape(split0).eval()

array([3, 1], dtype=int32)

* embedding lookup

In [89]:
ids = [[1,2], [0,1]]
res = tf.nn.embedding_lookup(matrix1, ids)
res.eval()

array([[[3, 4, 5],
        [6, 7, 8]],

       [[0, 1, 2],
        [3, 4, 5]]], dtype=int32)